runtime: python39
entrypoint: gunicorn -b :$PORT webapp.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "webapp.settings"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always 