services:
  - type: web
    name: cloud-project-1
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn webapp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-project-1-database
          property: connectionString
      - key: MONGODB_URI
        value: mongodb+srv://Namitha:NamiHarshu@866@cluster0.edzfz.mongodb.net/CloudProject?retryWrites=true&w=majority
      - key: FIREBASE_API_KEY
        value: AIzaSyDUEVU5icElBw_PR6xQ5XEXsy56vOL0H3g
      - key: FIREBASE_AUTH_DOMAIN
        value: cloud-project-1-27e81.firebaseapp.com
      - key: FIREBASE_DATABASE_URL
        value: https://cloudproject-bcd7008-default-rtdb.firebaseio.com
      - key: FIREBASE_PROJECT_ID
        value: cloud-project-1-27e81
      - key: FIREBASE_STORAGE_BUCKET
        value: cloud-project-1-27e81.appspot.com
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 850810687393
      - key: FIREBASE_APP_ID
        value: 1:850810687393:web:c3c448975108610c3345e0
      - key: FIREBASE_MEASUREMENT_ID
        value: G-Z40ZLL0MMJ
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: STATICFILES_STORAGE
        value: whitenoise.storage.CompressedManifestStaticFilesStorage
    healthCheckPath: /
    autoDeploy: true
    plan: free

  - type: pserv
    name: cloud-project-1-database
    env: postgres
    startCommand: postgres -D /var/lib/postgresql/data
    region: oregon
    plan: free