services:
  - type: web
    name: cloud-project-1
    env: python
    region: singapore  # Closest to India
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn webapp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-project-1-db
          property: connectionString
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_API_KEY
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_AUTH_DOMAIN
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_DATABASE_URL
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_PROJECT_ID
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_STORAGE_BUCKET
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_APP_ID
        sync: false  # Set this in Render dashboard
      - key: FIREBASE_MEASUREMENT_ID
        sync: false  # Set this in Render dashboard
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: STATIC_ROOT
        value: /opt/render/project/src/staticfiles
      - key: STATIC_URL
        value: /static/
      - key: STATICFILES_STORAGE
        value: whitenoise.storage.CompressedManifestStaticFilesStorage
    healthCheckPath: /
    autoDeploy: true
    plan: free

  - type: postgres
    name: cloud-project-1-db
    region: singapore
    plan: free
    ipAllowList: []  # only allow internal connections